-- =============================================================
-- PetFlow - SCRIPT COMPLETO ORACLE
-- Materia: Mastering Relational and Non-Relational Database
-- =============================================================
-- ORDEM DE EXECUCAO:
-- 1. DDL (criacao das tabelas)
-- 2. Tabela de log de erros
-- 3. Procedures de carga de dados
-- 4. Chamadas das procedures (carga inicial)
-- 5. Blocos anonimos de consulta (joins, group by, order by)
-- 6. Bloco LAG / LEAD (linha anterior, atual, proxima)
-- 7. Relatorios com cursor explicito
-- =============================================================


-- =============================================================
-- SECAO 1: DDL - CRIACAO DAS TABELAS
-- =============================================================

-- Limpa tabelas na ordem correta (filho antes do pai)
BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'REDEEM','COUPON','COUPON_TEMPLATE','PARTNER_DISCOUNT',
      'REWARD_POINT','RISK_SCORE','HEALTH_EVENT',
      'SUBSCRIPTION','PLAN','ADDRESS',
      'PET','CLINIC','TUTOR',
      'REWARD_ACTION','EVENT_TYPE','RISK_LEVEL','SPECIES',
      'LOG_ERROS', 'LOG_AUDITORIA_HEALTH_EVENT'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- -------------------------
-- Tabelas de dominio
-- -------------------------

CREATE TABLE species (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(50)  UNIQUE NOT NULL,
  description VARCHAR2(200)
);

CREATE TABLE event_type (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(50)  UNIQUE NOT NULL,
  points_reward NUMBER        NOT NULL,
  category      VARCHAR2(50)  NOT NULL
  -- categoria: 'PREVENTIVO', 'TERAPEUTICO', 'BEM_ESTAR', 'EMERGENCIA'
);

CREATE TABLE reward_action (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(50)  UNIQUE NOT NULL,
  points_value NUMBER        NOT NULL,
  description  VARCHAR2(200)
);

CREATE TABLE risk_level (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(50)  UNIQUE NOT NULL,
  description VARCHAR2(200),
  min_score   NUMBER        NOT NULL,
  max_score   NUMBER        NOT NULL
);

-- -------------------------
-- Entidades principais
-- -------------------------

CREATE TABLE tutor (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role          VARCHAR2(20) DEFAULT 'TUTOR' NOT NULL,  -- <-- ADICIONADO
  name          VARCHAR2(100) NOT NULL,
  email         VARCHAR2(100) UNIQUE NOT NULL,
  phone         VARCHAR2(20),
  password_hash VARCHAR2(255) NOT NULL,
  created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE address (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id  NUMBER        NOT NULL,
  street    VARCHAR2(200) NOT NULL,
  city      VARCHAR2(100) NOT NULL,
  state     VARCHAR2(50)  NOT NULL,
  zip_code  VARCHAR2(10)  NOT NULL,
  CONSTRAINT fk_address_tutor FOREIGN KEY (tutor_id) REFERENCES tutor(id)
);

CREATE TABLE clinic (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(100) NOT NULL,
  address    VARCHAR2(200),
  phone      VARCHAR2(20),
  cnpj       VARCHAR2(18)  UNIQUE,
  created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pet (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id   NUMBER        NOT NULL,
  species_id NUMBER        NOT NULL,
  name       VARCHAR2(100) NOT NULL,
  breed      VARCHAR2(50),
  birth_date DATE,
  weight     NUMBER(5,2),
  created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pet_tutor   FOREIGN KEY (tutor_id)   REFERENCES tutor(id),
  CONSTRAINT fk_pet_species FOREIGN KEY (species_id) REFERENCES species(id)
);

-- -------------------------
-- Planos e assinaturas
-- -------------------------

CREATE TABLE plan (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id        NUMBER        NOT NULL,
  name             VARCHAR2(100) NOT NULL,
  description      VARCHAR2(200),
  price            NUMBER(10,2)  NOT NULL,
  duration_days    NUMBER        NOT NULL,
  points_per_event NUMBER        DEFAULT 1 NOT NULL,
  -- multiplicador: plano premium pode dar 2x pontos por evento
  CONSTRAINT fk_plan_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id)
);

CREATE TABLE subscription (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id     NUMBER       NOT NULL,
  plan_id    NUMBER       NOT NULL,
  start_date DATE         NOT NULL,
  end_date   DATE,
  status     VARCHAR2(20) NOT NULL,
  -- status: 'ATIVO', 'ENCERRADO', 'CANCELADO'
  created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sub_pet  FOREIGN KEY (pet_id)  REFERENCES pet(id),
  CONSTRAINT fk_sub_plan FOREIGN KEY (plan_id) REFERENCES plan(id)
);

-- -------------------------
-- Saude do pet
-- -------------------------

CREATE TABLE health_event (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id        NUMBER        NOT NULL,
  event_type_id NUMBER        NOT NULL,
  clinic_id     NUMBER,
  description   VARCHAR2(200),
  event_date    DATE          NOT NULL,
  status        VARCHAR2(20)  NOT NULL,
  -- status: 'REALIZADO', 'PENDENTE', 'CANCELADO'
  created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_he_pet        FOREIGN KEY (pet_id)        REFERENCES pet(id),
  CONSTRAINT fk_he_event_type FOREIGN KEY (event_type_id) REFERENCES event_type(id),
  CONSTRAINT fk_he_clinic     FOREIGN KEY (clinic_id)     REFERENCES clinic(id)
);

-- -------------------------
-- Recompensas
-- -------------------------

CREATE TABLE reward_point (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id         NUMBER        NOT NULL,
  reward_action_id NUMBER        NOT NULL,
  points           NUMBER        NOT NULL,
  reference_type   VARCHAR2(50),
  -- ex: 'HEALTH_EVENT', 'SUBSCRIPTION', 'CADASTRO_PET'
  reference_id     NUMBER,
  -- id do registro que gerou os pontos
  created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rp_tutor  FOREIGN KEY (tutor_id)         REFERENCES tutor(id),
  CONSTRAINT fk_rp_action FOREIGN KEY (reward_action_id) REFERENCES reward_action(id)
);

-- -------------------------
-- Parceiros e cupons
-- -------------------------

CREATE TABLE partner_discount (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id        NUMBER        NOT NULL,
  partner_name     VARCHAR2(100) NOT NULL,
  category         VARCHAR2(50)  NOT NULL,
  -- categoria: 'RACAO', 'PETSHOP', 'MEDICAMENTO', 'CONSULTA'
  discount_percent NUMBER(5,2)   NOT NULL,
  CONSTRAINT fk_pd_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id)
);

CREATE TABLE coupon_template (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_discount_id NUMBER       NOT NULL,
  title              VARCHAR2(100) NOT NULL,
  discount_value     NUMBER(10,2)  NOT NULL,
  discount_type      VARCHAR2(20)  NOT NULL,
  -- tipo: 'PERCENTUAL', 'VALOR_FIXO'
  points_required    NUMBER        NOT NULL,
  CONSTRAINT fk_ct_partner FOREIGN KEY (partner_discount_id) REFERENCES partner_discount(id)
);

CREATE TABLE coupon (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id     NUMBER       NOT NULL,
  code            VARCHAR2(50) UNIQUE NOT NULL,
  status          VARCHAR2(20) NOT NULL,
  -- status: 'DISPONIVEL', 'RESGATADO', 'EXPIRADO'
  expiration_date DATE,
  created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_coupon_template FOREIGN KEY (template_id) REFERENCES coupon_template(id)
);

CREATE TABLE redeem (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id    NUMBER    NOT NULL,
  coupon_id   NUMBER    NOT NULL,
  points_used NUMBER    NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_redeem_tutor  FOREIGN KEY (tutor_id)  REFERENCES tutor(id),
  CONSTRAINT fk_redeem_coupon FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

-- -------------------------
-- Score de risco
-- -------------------------

CREATE TABLE risk_score (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id        NUMBER    NOT NULL,
  score         NUMBER    NOT NULL,
  risk_level_id NUMBER    NOT NULL,
  calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rs_pet   FOREIGN KEY (pet_id)        REFERENCES pet(id),
  CONSTRAINT fk_rs_level FOREIGN KEY (risk_level_id) REFERENCES risk_level(id)
);


-- =============================================================
-- SECAO 2: TABELA DE LOG DE ERROS
-- Usada por todas as procedures para registrar excecoes
-- =============================================================

CREATE TABLE log_erros (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  procedure_name   VARCHAR2(100) NOT NULL,
  usuario          VARCHAR2(100) NOT NULL,
  data_ocorrencia  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  codigo_erro      NUMBER,
  mensagem_erro    VARCHAR2(4000)
);


-- =============================================================
-- SECAO 3: PROCEDURES DE CARGA DE DADOS
-- Uma procedure por tabela, com passagem de parametros,
-- tratamento de excecao (WHEN OTHERS + 2 excecoes especificas)
-- e log de erros.
-- =============================================================

-- -------------------------
-- 3.1 SPECIES
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_species (
  p_name        IN species.name%TYPE,
  p_description IN species.description%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_nome_nulo   EXCEPTION;
  ex_duplicado   EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_duplicado, -1);
BEGIN
  v_usuario := USER;
  IF p_name IS NULL THEN
    RAISE ex_nome_nulo;
  END IF;

  INSERT INTO species (name, description)
  VALUES (p_name, p_description);

  COMMIT;

EXCEPTION
  WHEN ex_nome_nulo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_species', v_usuario, -20001, 'Nome da especie nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20001, 'Nome da especie nao pode ser nulo');

  WHEN ex_duplicado THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_species', v_usuario, -1, 'Especie ja cadastrada: ' || p_name);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20002, 'Especie ja cadastrada: ' || p_name);

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_species', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_species;
/

-- -------------------------
-- 3.2 EVENT_TYPE
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_event_type (
  p_name          IN event_type.name%TYPE,
  p_points_reward IN event_type.points_reward%TYPE,
  p_category      IN event_type.category%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_pontos_invalidos EXCEPTION;
  ex_duplicado        EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_duplicado, -1);
BEGIN
  v_usuario := USER;
  IF p_points_reward < 0 THEN
    RAISE ex_pontos_invalidos;
  END IF;

  INSERT INTO event_type (name, points_reward, category)
  VALUES (p_name, p_points_reward, p_category);

  COMMIT;

EXCEPTION
  WHEN ex_pontos_invalidos THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_event_type', v_usuario, -20003, 'Pontos nao podem ser negativos');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20003, 'Pontos nao podem ser negativos');

  WHEN ex_duplicado THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_event_type', v_usuario, -1, 'Tipo de evento ja existe: ' || p_name);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20004, 'Tipo de evento ja existe: ' || p_name);

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_event_type', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_event_type;
/

-- -------------------------
-- 3.3 REWARD_ACTION
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_reward_action (
  p_name         IN reward_action.name%TYPE,
  p_points_value IN reward_action.points_value%TYPE,
  p_description  IN reward_action.description%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_duplicado       EXCEPTION;
  ex_pontos_invalidos EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_duplicado, -1);
BEGIN
  v_usuario := USER;
  IF p_points_value <= 0 THEN
    RAISE ex_pontos_invalidos;
  END IF;

  INSERT INTO reward_action (name, points_value, description)
  VALUES (p_name, p_points_value, p_description);

  COMMIT;

EXCEPTION
  WHEN ex_pontos_invalidos THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_reward_action', v_usuario, -20005, 'Valor dos pontos deve ser maior que zero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20005, 'Valor dos pontos deve ser maior que zero');

  WHEN ex_duplicado THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_reward_action', v_usuario, -1, 'Acao de recompensa ja existe: ' || p_name);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20006, 'Acao de recompensa ja existe: ' || p_name);

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_reward_action', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_reward_action;
/

-- -------------------------
-- 3.4 RISK_LEVEL
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_risk_level (
  p_name        IN risk_level.name%TYPE,
  p_description IN risk_level.description%TYPE,
  p_min_score   IN risk_level.min_score%TYPE,
  p_max_score   IN risk_level.max_score%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_intervalo_invalido EXCEPTION;
  ex_duplicado          EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_duplicado, -1);
BEGIN
  v_usuario := USER;
  IF p_min_score > p_max_score THEN
    RAISE ex_intervalo_invalido;
  END IF;

  INSERT INTO risk_level (name, description, min_score, max_score)
  VALUES (p_name, p_description, p_min_score, p_max_score);

  COMMIT;

EXCEPTION
  WHEN ex_intervalo_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_risk_level', v_usuario, -20007, 'Score minimo nao pode ser maior que o maximo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20007, 'Score minimo nao pode ser maior que o maximo');

  WHEN ex_duplicado THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_risk_level', v_usuario, -1, 'Nivel de risco ja existe: ' || p_name);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20008, 'Nivel de risco ja existe: ' || p_name);

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_risk_level', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_risk_level;
/

-- -------------------------
-- 3.5 TUTOR
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_tutor (
  p_role          IN tutor.role%TYPE DEFAULT 'TUTOR',
  p_name          IN tutor.name%TYPE,
  p_email         IN tutor.email%TYPE,
  p_phone         IN tutor.phone%TYPE,
  p_password_hash IN tutor.password_hash%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_email_nulo EXCEPTION;
  ex_duplicado  EXCEPTION;
  ex_role_invalido EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_duplicado, -1);
BEGIN
  v_usuario := USER;
  
  -- Nova validação para ROLE
  IF p_role NOT IN ('ADMIN', 'TUTOR') THEN
    RAISE ex_role_invalido;
  END IF;
  
  IF p_email IS NULL THEN
    RAISE ex_email_nulo;
  END IF;

  INSERT INTO tutor (role, name, email, phone, password_hash)
  VALUES (p_role, p_name, p_email, p_phone, p_password_hash);

  COMMIT;

EXCEPTION
  WHEN ex_email_nulo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_tutor', v_usuario, -20009, 'Email do tutor nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20009, 'Email do tutor nao pode ser nulo');

  WHEN ex_duplicado THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_tutor', v_usuario, -1, 'Email ja cadastrado: ' || p_email);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20010, 'Email ja cadastrado: ' || p_email);
  
  WHEN ex_role_invalido THEN  -- <-- NOVA EXCEÇÃO
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_tutor', v_usuario, -20035, 'Role invalida. Use ADMIN ou TUTOR');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20035, 'Role invalida. Use ADMIN ou TUTOR');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_tutor', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_tutor;
/

-- -------------------------
-- 3.6 ADDRESS
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_address (
  p_tutor_id IN address.tutor_id%TYPE,
  p_street   IN address.street%TYPE,
  p_city     IN address.city%TYPE,
  p_state    IN address.state%TYPE,
  p_zip_code IN address.zip_code%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_tutor_invalido EXCEPTION;
  ex_cep_invalido   EXCEPTION;
  v_count           NUMBER;
BEGIN
  v_usuario := USER;
  SELECT COUNT(*) INTO v_count FROM tutor WHERE id = p_tutor_id;
  IF v_count = 0 THEN
    RAISE ex_tutor_invalido;
  END IF;

  IF LENGTH(p_zip_code) < 8 THEN
    RAISE ex_cep_invalido;
  END IF;

  INSERT INTO address (tutor_id, street, city, state, zip_code)
  VALUES (p_tutor_id, p_street, p_city, p_state, p_zip_code);

  COMMIT;

EXCEPTION
  WHEN ex_tutor_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_address', v_usuario, -20011, 'Tutor nao encontrado: ID ' || p_tutor_id);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20011, 'Tutor nao encontrado');

  WHEN ex_cep_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_address', v_usuario, -20012, 'CEP invalido: ' || p_zip_code);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20012, 'CEP invalido');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_address', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_address;
/

-- -------------------------
-- 3.7 CLINIC
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_clinic (
  p_name    IN clinic.name%TYPE,
  p_address IN clinic.address%TYPE,
  p_phone   IN clinic.phone%TYPE,
  p_cnpj    IN clinic.cnpj%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_duplicado EXCEPTION;
  ex_nome_nulo EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_duplicado, -1);
BEGIN
  v_usuario := USER;
  IF p_name IS NULL THEN
    RAISE ex_nome_nulo;
  END IF;

  INSERT INTO clinic (name, address, phone, cnpj)
  VALUES (p_name, p_address, p_phone, p_cnpj);

  COMMIT;

EXCEPTION
  WHEN ex_nome_nulo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_clinic', v_usuario, -20013, 'Nome da clinica nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20013, 'Nome da clinica nao pode ser nulo');

  WHEN ex_duplicado THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_clinic', v_usuario, -1, 'CNPJ ja cadastrado: ' || p_cnpj);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20014, 'CNPJ ja cadastrado');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_clinic', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_clinic;
/

-- -------------------------
-- 3.8 PET
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_pet (
  p_tutor_id   IN pet.tutor_id%TYPE,
  p_species_id IN pet.species_id%TYPE,
  p_name       IN pet.name%TYPE,
  p_breed      IN pet.breed%TYPE,
  p_birth_date IN pet.birth_date%TYPE,
  p_weight     IN pet.weight%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_nome_nulo  EXCEPTION;
  ex_peso_invalido EXCEPTION;
  v_count       NUMBER;
BEGIN
  v_usuario := USER;
  IF p_name IS NULL THEN
    RAISE ex_nome_nulo;
  END IF;

  IF p_weight IS NOT NULL AND p_weight <= 0 THEN
    RAISE ex_peso_invalido;
  END IF;

  INSERT INTO pet (tutor_id, species_id, name, breed, birth_date, weight)
  VALUES (p_tutor_id, p_species_id, p_name, p_breed, p_birth_date, p_weight);

  COMMIT;

EXCEPTION
  WHEN ex_nome_nulo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_pet', v_usuario, -20015, 'Nome do pet nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20015, 'Nome do pet nao pode ser nulo');

  WHEN ex_peso_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_pet', v_usuario, -20016, 'Peso do pet deve ser maior que zero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20016, 'Peso do pet deve ser maior que zero');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_pet', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_pet;
/

-- -------------------------
-- 3.9 PLAN
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_plan (
  p_clinic_id        IN plan.clinic_id%TYPE,
  p_name             IN plan.name%TYPE,
  p_description      IN plan.description%TYPE,
  p_price            IN plan.price%TYPE,
  p_duration_days    IN plan.duration_days%TYPE,
  p_points_per_event IN plan.points_per_event%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_preco_invalido    EXCEPTION;
  ex_duracao_invalida  EXCEPTION;
BEGIN
  v_usuario := USER;
  IF p_price <= 0 THEN
    RAISE ex_preco_invalido;
  END IF;

  IF p_duration_days <= 0 THEN
    RAISE ex_duracao_invalida;
  END IF;

  INSERT INTO plan (clinic_id, name, description, price, duration_days, points_per_event)
  VALUES (p_clinic_id, p_name, p_description, p_price, p_duration_days, p_points_per_event);

  COMMIT;

EXCEPTION
  WHEN ex_preco_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_plan', v_usuario, -20017, 'Preco do plano deve ser maior que zero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20017, 'Preco do plano deve ser maior que zero');

  WHEN ex_duracao_invalida THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_plan', v_usuario, -20018, 'Duracao do plano deve ser maior que zero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20018, 'Duracao do plano deve ser maior que zero');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_plan', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_plan;
/

-- -------------------------
-- 3.10 SUBSCRIPTION
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_subscription (
  p_pet_id     IN subscription.pet_id%TYPE,
  p_plan_id    IN subscription.plan_id%TYPE,
  p_start_date IN subscription.start_date%TYPE,
  p_end_date   IN subscription.end_date%TYPE,
  p_status     IN subscription.status%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_data_invalida EXCEPTION;
  ex_status_invalido EXCEPTION;
BEGIN
  v_usuario := USER;
  IF p_end_date IS NOT NULL AND p_end_date < p_start_date THEN
    RAISE ex_data_invalida;
  END IF;

  IF p_status NOT IN ('ATIVO','ENCERRADO','CANCELADO') THEN
    RAISE ex_status_invalido;
  END IF;

  INSERT INTO subscription (pet_id, plan_id, start_date, end_date, status)
  VALUES (p_pet_id, p_plan_id, p_start_date, p_end_date, p_status);

  COMMIT;

EXCEPTION
  WHEN ex_data_invalida THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_subscription', v_usuario, -20019, 'Data de fim nao pode ser anterior a data de inicio');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20019, 'Data de fim invalida');

  WHEN ex_status_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_subscription', v_usuario, -20020, 'Status invalido: ' || p_status);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20020, 'Status invalido. Use: ATIVO, ENCERRADO ou CANCELADO');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_subscription', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_subscription;
/

-- -------------------------
-- 3.11 HEALTH_EVENT
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_health_event (
  p_pet_id        IN health_event.pet_id%TYPE,
  p_event_type_id IN health_event.event_type_id%TYPE,
  p_clinic_id     IN health_event.clinic_id%TYPE,
  p_description   IN health_event.description%TYPE,
  p_event_date    IN health_event.event_date%TYPE,
  p_status        IN health_event.status%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_data_futura   EXCEPTION;
  ex_status_invalido EXCEPTION;
BEGIN
  v_usuario := USER;
  IF p_event_date > SYSDATE THEN
    RAISE ex_data_futura;
  END IF;

  IF p_status NOT IN ('REALIZADO','PENDENTE','CANCELADO') THEN
    RAISE ex_status_invalido;
  END IF;

  INSERT INTO health_event (pet_id, event_type_id, clinic_id, description, event_date, status)
  VALUES (p_pet_id, p_event_type_id, p_clinic_id, p_description, p_event_date, p_status);

  COMMIT;

EXCEPTION
  WHEN ex_data_futura THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_health_event', v_usuario, -20021, 'Data do evento nao pode ser futura');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20021, 'Data do evento nao pode ser futura');

  WHEN ex_status_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_health_event', v_usuario, -20022, 'Status invalido: ' || p_status);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20022, 'Status invalido');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_health_event', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_health_event;
/

-- -------------------------
-- 3.12 REWARD_POINT
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_reward_point (
  p_tutor_id         IN reward_point.tutor_id%TYPE,
  p_reward_action_id IN reward_point.reward_action_id%TYPE,
  p_points           IN reward_point.points%TYPE,
  p_reference_type   IN reward_point.reference_type%TYPE,
  p_reference_id     IN reward_point.reference_id%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_pontos_invalidos EXCEPTION;
  ex_referencia_nula  EXCEPTION;
BEGIN
  v_usuario := USER;
  IF p_points <= 0 THEN
    RAISE ex_pontos_invalidos;
  END IF;

  IF p_reference_type IS NULL THEN
    RAISE ex_referencia_nula;
  END IF;

  INSERT INTO reward_point (tutor_id, reward_action_id, points, reference_type, reference_id)
  VALUES (p_tutor_id, p_reward_action_id, p_points, p_reference_type, p_reference_id);

  COMMIT;

EXCEPTION
  WHEN ex_pontos_invalidos THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_reward_point', v_usuario, -20023, 'Pontos devem ser maiores que zero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20023, 'Pontos devem ser maiores que zero');

  WHEN ex_referencia_nula THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_reward_point', v_usuario, -20024, 'Tipo de referencia nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20024, 'Tipo de referencia nao pode ser nulo');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_reward_point', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_reward_point;
/

-- -------------------------
-- 3.13 PARTNER_DISCOUNT
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_partner_discount (
  p_clinic_id        IN partner_discount.clinic_id%TYPE,
  p_partner_name     IN partner_discount.partner_name%TYPE,
  p_category         IN partner_discount.category%TYPE,
  p_discount_percent IN partner_discount.discount_percent%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_desconto_invalido EXCEPTION;
  ex_nome_nulo         EXCEPTION;
BEGIN
  v_usuario := USER;
  IF p_partner_name IS NULL THEN
    RAISE ex_nome_nulo;
  END IF;

  IF p_discount_percent <= 0 OR p_discount_percent > 100 THEN
    RAISE ex_desconto_invalido;
  END IF;

  INSERT INTO partner_discount (clinic_id, partner_name, category, discount_percent)
  VALUES (p_clinic_id, p_partner_name, p_category, p_discount_percent);

  COMMIT;

EXCEPTION
  WHEN ex_nome_nulo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_partner_discount', v_usuario, -20025, 'Nome do parceiro nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20025, 'Nome do parceiro nao pode ser nulo');

  WHEN ex_desconto_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_partner_discount', v_usuario, -20026, 'Desconto deve estar entre 1 e 100');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20026, 'Percentual de desconto invalido');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_partner_discount', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_partner_discount;
/

-- -------------------------
-- 3.14 COUPON_TEMPLATE
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_coupon_template (
  p_partner_discount_id IN coupon_template.partner_discount_id%TYPE,
  p_title               IN coupon_template.title%TYPE,
  p_discount_value      IN coupon_template.discount_value%TYPE,
  p_discount_type       IN coupon_template.discount_type%TYPE,
  p_points_required     IN coupon_template.points_required%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_tipo_invalido      EXCEPTION;
  ex_pontos_invalidos   EXCEPTION;
BEGIN
  v_usuario := USER;
  IF p_discount_type NOT IN ('PERCENTUAL','VALOR_FIXO') THEN
    RAISE ex_tipo_invalido;
  END IF;

  IF p_points_required <= 0 THEN
    RAISE ex_pontos_invalidos;
  END IF;

  INSERT INTO coupon_template (partner_discount_id, title, discount_value, discount_type, points_required)
  VALUES (p_partner_discount_id, p_title, p_discount_value, p_discount_type, p_points_required);

  COMMIT;

EXCEPTION
  WHEN ex_tipo_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_coupon_template', v_usuario, -20027, 'Tipo de desconto invalido: ' || p_discount_type);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20027, 'Use PERCENTUAL ou VALOR_FIXO');

  WHEN ex_pontos_invalidos THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_coupon_template', v_usuario, -20028, 'Pontos necessarios devem ser maiores que zero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20028, 'Pontos necessarios invalidos');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_coupon_template', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_coupon_template;
/

-- -------------------------
-- 3.15 COUPON
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_coupon (
  p_template_id     IN coupon.template_id%TYPE,
  p_code            IN coupon.code%TYPE,
  p_status          IN coupon.status%TYPE,
  p_expiration_date IN coupon.expiration_date%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_duplicado    EXCEPTION;
  ex_status_invalido EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_duplicado, -1);
BEGIN
  v_usuario := USER;
  IF p_status NOT IN ('DISPONIVEL','RESGATADO','EXPIRADO') THEN
    RAISE ex_status_invalido;
  END IF;

  INSERT INTO coupon (template_id, code, status, expiration_date)
  VALUES (p_template_id, p_code, p_status, p_expiration_date);

  COMMIT;

EXCEPTION
  WHEN ex_status_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_coupon', v_usuario, -20029, 'Status de cupom invalido: ' || p_status);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20029, 'Status invalido');

  WHEN ex_duplicado THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_coupon', v_usuario, -1, 'Codigo de cupom ja existe: ' || p_code);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20030, 'Codigo de cupom duplicado');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_coupon', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_coupon;
/

-- -------------------------
-- 3.16 REDEEM
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_redeem (
  p_tutor_id   IN redeem.tutor_id%TYPE,
  p_coupon_id  IN redeem.coupon_id%TYPE,
  p_points_used IN redeem.points_used%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_pontos_invalidos EXCEPTION;
  ex_cupom_indisponivel EXCEPTION;
  v_status VARCHAR2(20);
BEGIN
  v_usuario := USER;
  IF p_points_used <= 0 THEN
    RAISE ex_pontos_invalidos;
  END IF;

  SELECT status INTO v_status FROM coupon WHERE id = p_coupon_id;
  IF v_status != 'DISPONIVEL' THEN
    RAISE ex_cupom_indisponivel;
  END IF;

  INSERT INTO redeem (tutor_id, coupon_id, points_used)
  VALUES (p_tutor_id, p_coupon_id, p_points_used);

  UPDATE coupon SET status = 'RESGATADO' WHERE id = p_coupon_id;

  COMMIT;

EXCEPTION
  WHEN ex_pontos_invalidos THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_redeem', v_usuario, -20031, 'Pontos usados devem ser maiores que zero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20031, 'Pontos invalidos');

  WHEN ex_cupom_indisponivel THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_redeem', v_usuario, -20032, 'Cupom nao esta disponivel para resgate');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20032, 'Cupom indisponivel');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_redeem', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_redeem;
/

-- -------------------------
-- 3.17 RISK_SCORE
-- -------------------------
CREATE OR REPLACE PROCEDURE sp_insert_risk_score (
  p_pet_id        IN risk_score.pet_id%TYPE,
  p_score         IN risk_score.score%TYPE,
  p_risk_level_id IN risk_score.risk_level_id%TYPE
) AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);
  ex_score_invalido EXCEPTION;
  ex_nivel_invalido EXCEPTION;
  v_count NUMBER;
BEGIN
  v_usuario := USER;
  IF p_score < 0 OR p_score > 100 THEN
    RAISE ex_score_invalido;
  END IF;

  SELECT COUNT(*) INTO v_count FROM risk_level WHERE id = p_risk_level_id;
  IF v_count = 0 THEN
    RAISE ex_nivel_invalido;
  END IF;

  INSERT INTO risk_score (pet_id, score, risk_level_id)
  VALUES (p_pet_id, p_score, p_risk_level_id);

  COMMIT;

EXCEPTION
  WHEN ex_score_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_risk_score', v_usuario, -20033, 'Score deve estar entre 0 e 100');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20033, 'Score invalido');

  WHEN ex_nivel_invalido THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_risk_score', v_usuario, -20034, 'Nivel de risco nao encontrado: ID ' || p_risk_level_id);
    COMMIT;
    RAISE_APPLICATION_ERROR(-20034, 'Nivel de risco invalido');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_insert_risk_score', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_insert_risk_score;
/


-- =============================================================
-- SECAO 4: CARGA DE DADOS (chamadas das procedures)
-- =============================================================

-- Species
BEGIN sp_insert_species('Cachorro', 'Canis lupus familiaris'); END;
/
BEGIN sp_insert_species('Gato',     'Felis catus'); END;
/
BEGIN sp_insert_species('Coelho',   'Oryctolagus cuniculus'); END;
/
BEGIN sp_insert_species('Ave',      'Aves diversas'); END;
/
BEGIN sp_insert_species('Hamster',  'Cricetinae spp.'); END;
/

-- Event Types
BEGIN sp_insert_event_type('Vacina Antirabica',   50, 'PREVENTIVO'); END;
/
BEGIN sp_insert_event_type('Vermifugacao',         30, 'PREVENTIVO'); END;
/
BEGIN sp_insert_event_type('Consulta de Retorno',  40, 'TERAPEUTICO'); END;
/
BEGIN sp_insert_event_type('Check-up Anual',       60, 'PREVENTIVO'); END;
/
BEGIN sp_insert_event_type('Banho e Tosa',         20, 'BEM_ESTAR'); END;
/
BEGIN sp_insert_event_type('Exame de Sangue',      45, 'TERAPEUTICO'); END;
/
BEGIN sp_insert_event_type('Cirurgia',             80, 'TERAPEUTICO'); END;
/
BEGIN sp_insert_event_type('Emergencia',           70, 'EMERGENCIA'); END;
/

-- Reward Actions
BEGIN sp_insert_reward_action('Registrar Evento de Saude', 50, 'Pontua ao registrar qualquer evento clinico'); END;
/
BEGIN sp_insert_reward_action('Cadastrar Pet',             100, 'Bonus ao cadastrar o primeiro pet'); END;
/
BEGIN sp_insert_reward_action('Assinar Plano',             200, 'Bonus ao ativar uma assinatura'); END;
/
BEGIN sp_insert_reward_action('Indicar Amigo',             150, 'Bonus por indicacao de novo tutor'); END;
/

-- Risk Levels
BEGIN sp_insert_risk_level('Baixo',  'Pet saudavel e em dia com preventivos', 0,  30); END;
/
BEGIN sp_insert_risk_level('Medio',  'Atencao recomendada',                   31, 60); END;
/
BEGIN sp_insert_risk_level('Alto',   'Requer acompanhamento proximo',         61, 80); END;
/
BEGIN sp_insert_risk_level('Critico','Intervencao urgente necessaria',         81,100); END;
/

-- Clinics
BEGIN sp_insert_clinic('Clinica VetVida',    'Rua das Flores, 100 - Sao Paulo',   '11-91111-1111', '12.345.678/0001-90'); END;
/
BEGIN sp_insert_clinic('Hospital PetCare',   'Av. Paulista, 500 - Sao Paulo',     '11-92222-2222', '98.765.432/0001-11'); END;
/
BEGIN sp_insert_clinic('Vet Animal Premium', 'Rua Augusta, 200 - Sao Paulo',      '11-93333-3333', '11.222.333/0001-44'); END;
/

-- Tutors (com ROLE)
BEGIN sp_insert_tutor('TUTOR', 'Ana Lima',     'ana.lima@email.com',     '11-98001-0001', 'hash_ana_123'); END;
/
BEGIN sp_insert_tutor('TUTOR', 'Bruno Silva',  'bruno.silva@email.com',  '11-98002-0002', 'hash_bruno_456'); END;
/
BEGIN sp_insert_tutor('TUTOR', 'Carla Souza',  'carla.souza@email.com',  '11-98003-0003', 'hash_carla_789'); END;
/
BEGIN sp_insert_tutor('TUTOR', 'Diego Martins','diego.martins@email.com','11-98004-0004', 'hash_diego_012'); END;
/
BEGIN sp_insert_tutor('TUTOR', 'Eduarda Costa','eduarda.costa@email.com','11-98005-0005', 'hash_edu_345'); END;
/
BEGIN sp_insert_tutor('TUTOR', 'Felipe Nunes', 'felipe.nunes@email.com', '11-98006-0006', 'hash_fe_678'); END;
/
BEGIN sp_insert_tutor('TUTOR', 'Maria Souza', 'maria@petflow.com', '(11) 98888-1234', '$2b$10$/vPZqCCwPJSroSMducM2T.ZEgB9RFu2vz4K0jAoy3o10erMPVqJmu'); END;
/

-- Administrador (ROLE ADMIN)
BEGIN sp_insert_tutor('ADMIN', 'Administrador PetFlow', 'admin@petflow.com', '(11) 90000-0000', '$2b$10$h5iXTBt/JpyOL/.UE2bmM.QvC3W/wCSb7M75bMI1Y.6Fn7D1cVWjS'); END;
/

-- Addresses
BEGIN sp_insert_address(1,'Rua das Acacias, 10',   'Sao Paulo','SP','01310100'); END;
/
BEGIN sp_insert_address(2,'Av. Brasil, 200',        'Campinas', 'SP','13010100'); END;
/
BEGIN sp_insert_address(3,'Rua XV de Novembro, 30','Curitiba',  'PR','80010010'); END;
/
BEGIN sp_insert_address(4,'Rua Goias, 50',          'Goiania',  'GO','74010020'); END;
/
BEGIN sp_insert_address(5,'Av. Afonso Pena, 700',  'Belo Horizonte','MG','30130005'); END;
/
BEGIN sp_insert_address(6,'Rua da Paz, 90',         'Porto Alegre','RS','90010090'); END;
/

-- Pets
BEGIN sp_insert_pet(1, 1, 'Rex',    'Labrador',    DATE '2020-03-15', 28.5); END;
/
BEGIN sp_insert_pet(1, 2, 'Mimi',   'Persa',       DATE '2019-07-20', 4.2); END;
/
BEGIN sp_insert_pet(2, 1, 'Thor',   'Golden',      DATE '2021-01-10', 32.0); END;
/
BEGIN sp_insert_pet(3, 2, 'Luna',   'Siames',      DATE '2022-05-05', 3.8); END;
/
BEGIN sp_insert_pet(3, 1, 'Bolt',   'Beagle',      DATE '2018-11-30', 14.0); END;
/
BEGIN sp_insert_pet(4, 3, 'Fofo',   'Angorá',      DATE '2023-02-14', 1.2); END;
/
BEGIN sp_insert_pet(5, 1, 'Duque',  'Poodle',      DATE '2020-08-22', 8.5); END;
/
BEGIN sp_insert_pet(5, 2, 'Nala',   'Maine Coon',  DATE '2021-12-01', 5.6); END;
/
BEGIN sp_insert_pet(6, 4, 'Piu',    'Calopsita',   DATE '2022-04-10', 0.09); END;
/
BEGIN sp_insert_pet(6, 5, 'Bolota', 'Hamster Anão',DATE '2023-06-01', 0.04); END;
/

-- Plans
BEGIN sp_insert_plan(1,'Plano Basico VetVida',    'Cobertura basica de preventivos',  89.90,  30, 1); END;
/
BEGIN sp_insert_plan(1,'Plano Premium VetVida',   'Cobertura completa + 2x pontos',  199.90, 30, 2); END;
/
BEGIN sp_insert_plan(2,'Plano PetCare Essencial', 'Check-up mensal incluido',         99.90,  30, 1); END;
/
BEGIN sp_insert_plan(3,'Plano Anual Vet Premium', 'Melhor custo beneficio anual',    149.90, 365, 2); END;
/

-- Subscriptions
BEGIN sp_insert_subscription(1, 2, DATE '2025-01-01', DATE '2025-12-31', 'ATIVO'); END;
/
BEGIN sp_insert_subscription(2, 1, DATE '2025-02-01', DATE '2025-07-31', 'ATIVO'); END;
/
BEGIN sp_insert_subscription(3, 3, DATE '2025-01-15', DATE '2025-07-15', 'ATIVO'); END;
/
BEGIN sp_insert_subscription(4, 4, DATE '2024-06-01', DATE '2025-05-31', 'ATIVO'); END;
/
BEGIN sp_insert_subscription(5, 1, DATE '2025-03-01', DATE '2025-08-31', 'ATIVO'); END;
/
BEGIN sp_insert_subscription(7, 2, DATE '2025-01-01', DATE '2025-06-30', 'ENCERRADO'); END;
/

-- Health Events
BEGIN sp_insert_health_event(1, 1, 1, 'Antirabica anual aplicada',      DATE '2025-01-10', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(1, 2, 1, 'Vermifugacao trimestral',        DATE '2025-02-05', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(2, 5, 1, 'Banho e tosa completa',          DATE '2025-01-20', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(3, 4, 2, 'Check-up anual sem alteracoes',  DATE '2025-02-15', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(3, 6, 2, 'Exame de sangue - hemograma',    DATE '2025-03-01', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(4, 3, 3, 'Retorno pos-cirurgia ok',        DATE '2025-01-25', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(5, 1, 1, 'Vacina V10 aplicada',            DATE '2025-03-10', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(6, 2, 3, 'Vermifugacao coelho',            DATE '2025-02-28', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(7, 4, 1, 'Check-up poodle',                DATE '2025-04-01', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(8, 5, 2, 'Banho gato maine coon',          DATE '2025-04-05', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(1, 6, 2, 'Exame bioquimico completo',      DATE '2025-04-10', 'REALIZADO'); END;
/
BEGIN sp_insert_health_event(3, 1, 1, 'Antirabica beagle',              DATE '2025-04-12', 'REALIZADO'); END;
/

-- Reward Points
BEGIN sp_insert_reward_point(1, 1,  50, 'HEALTH_EVENT', 1); END;
/
BEGIN sp_insert_reward_point(1, 1,  30, 'HEALTH_EVENT', 2); END;
/
BEGIN sp_insert_reward_point(1, 2, 100, 'CADASTRO_PET', 1); END;
/
BEGIN sp_insert_reward_point(1, 3, 200, 'SUBSCRIPTION', 1); END;
/
BEGIN sp_insert_reward_point(2, 1,  20, 'HEALTH_EVENT', 3); END;
/
BEGIN sp_insert_reward_point(2, 2, 100, 'CADASTRO_PET', 3); END;
/
BEGIN sp_insert_reward_point(3, 1,  60, 'HEALTH_EVENT', 4); END;
/
BEGIN sp_insert_reward_point(3, 1,  45, 'HEALTH_EVENT', 5); END;
/
BEGIN sp_insert_reward_point(3, 3, 200, 'SUBSCRIPTION', 3); END;
/
BEGIN sp_insert_reward_point(4, 1,  40, 'HEALTH_EVENT', 6); END;
/
BEGIN sp_insert_reward_point(5, 1,  50, 'HEALTH_EVENT', 7); END;
/
BEGIN sp_insert_reward_point(5, 4, 150, 'INDICACAO',    NULL); END;
/

-- Partner Discounts
BEGIN sp_insert_partner_discount(1, 'PetShop PataFeliz', 'PETSHOP',    15.00); END;
/
BEGIN sp_insert_partner_discount(1, 'RacaoMax',          'RACAO',      10.00); END;
/
BEGIN sp_insert_partner_discount(2, 'FarmaVet',          'MEDICAMENTO', 20.00); END;
/

-- Coupon Templates
BEGIN sp_insert_coupon_template(1, '15% OFF em produtos PataFeliz', 15.00, 'PERCENTUAL', 300); END;
/
BEGIN sp_insert_coupon_template(2, 'R$20 OFF em racao premium',     20.00, 'VALOR_FIXO',  200); END;
/
BEGIN sp_insert_coupon_template(3, '20% OFF em medicamentos',        20.00, 'PERCENTUAL', 400); END;
/

-- Coupons
BEGIN sp_insert_coupon(1, 'PATA15-2025-A1', 'DISPONIVEL', DATE '2025-12-31'); END;
/
BEGIN sp_insert_coupon(1, 'PATA15-2025-A2', 'DISPONIVEL', DATE '2025-12-31'); END;
/
BEGIN sp_insert_coupon(2, 'RACAO20-2025-B1','DISPONIVEL', DATE '2025-09-30'); END;
/
BEGIN sp_insert_coupon(3, 'FARMA20-2025-C1','DISPONIVEL', DATE '2025-12-31'); END;
/

-- Redeems (tutor 1 tem pontos suficientes)
BEGIN sp_insert_redeem(1, 1, 300); END;
/
BEGIN sp_insert_redeem(3, 3, 400); END;
/

-- Risk Scores
BEGIN sp_insert_risk_score(1,  15, 1); END;
/
BEGIN sp_insert_risk_score(2,  22, 1); END;
/
BEGIN sp_insert_risk_score(3,  45, 2); END;
/
BEGIN sp_insert_risk_score(4,  68, 3); END;
/
BEGIN sp_insert_risk_score(5,  35, 2); END;
/
BEGIN sp_insert_risk_score(6,  12, 1); END;
/
BEGIN sp_insert_risk_score(7,  55, 2); END;
/
BEGIN sp_insert_risk_score(8,  20, 1); END;
/


-- =============================================================
-- SECAO 5: BLOCOS ANONIMOS DE CONSULTA (JOINS + GROUP BY + ORDER BY)
-- Requisito: pelo menos 3 consultas de juncao com agrupamento e ordenacao
-- =============================================================

-- -------------------------
-- Bloco 5.1
-- Ranking de tutores por total de pontos acumulados
-- JOIN: tutor x reward_point x reward_action
-- -------------------------
DECLARE
  v_linha VARCHAR2(200);
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('RANKING DE TUTORES POR PONTOS ACUMULADOS');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Tutor',25) || RPAD('Acoes',20) || LPAD('Total Pontos',15));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));

  FOR r IN (
    SELECT
      t.name                       AS tutor_nome,
      COUNT(rp.id)                 AS qtd_acoes,
      SUM(rp.points)               AS total_pontos
    FROM tutor t
    JOIN reward_point rp ON rp.tutor_id = t.id
    JOIN reward_action ra ON ra.id = rp.reward_action_id
    GROUP BY t.name
    ORDER BY total_pontos DESC
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.tutor_nome, 25) ||
      RPAD(r.qtd_acoes,  20) ||
      LPAD(r.total_pontos, 15)
    );
  END LOOP;
END;
/

-- -------------------------
-- Bloco 5.2
-- Eventos de saude por tipo e clinica
-- JOIN: health_event x event_type x clinic x pet
-- -------------------------
DECLARE
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('EVENTOS DE SAUDE POR TIPO E CLINICA');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Clinica',25) || RPAD('Tipo Evento',25) || LPAD('Qtd',10) || LPAD('Pts Gerados',15));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',75,'-'));

  FOR r IN (
    SELECT
      c.name                          AS clinica,
      et.name                         AS tipo_evento,
      et.category                     AS categoria,
      COUNT(he.id)                    AS quantidade,
      SUM(et.points_reward)           AS total_pts
    FROM health_event he
    JOIN event_type et ON et.id = he.event_type_id
    JOIN clinic c      ON c.id  = he.clinic_id
    JOIN pet p         ON p.id  = he.pet_id
    GROUP BY c.name, et.name, et.category
    ORDER BY c.name, total_pts DESC
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.clinica,      25) ||
      RPAD(r.tipo_evento,  25) ||
      LPAD(r.quantidade,   10) ||
      LPAD(r.total_pts,    15)
    );
  END LOOP;
END;
/

-- -------------------------
-- Bloco 5.3
-- Resumo de assinaturas ativas por plano e clinica
-- JOIN: subscription x plan x clinic x pet x tutor
-- -------------------------
DECLARE
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('ASSINATURAS ATIVAS POR PLANO E CLINICA');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Clinica',25) || RPAD('Plano',30) || LPAD('Assinaturas',15) || LPAD('Receita (R$)',15));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',85,'-'));

  FOR r IN (
    SELECT
      c.name                     AS clinica,
      pl.name                    AS plano,
      COUNT(s.id)                AS total_assinaturas,
      SUM(pl.price)              AS receita_total
    FROM subscription s
    JOIN plan pl  ON pl.id = s.plan_id
    JOIN clinic c ON c.id  = pl.clinic_id
    JOIN pet p    ON p.id  = s.pet_id
    WHERE s.status = 'ATIVO'
    GROUP BY c.name, pl.name, pl.price
    ORDER BY receita_total DESC
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.clinica,            25) ||
      RPAD(r.plano,              30) ||
      LPAD(r.total_assinaturas,  15) ||
      LPAD(TO_CHAR(r.receita_total,'FM99990.00'), 15)
    );
  END LOOP;
END;
/


-- =============================================================
-- SECAO 6: BLOCO LAG / LEAD
-- Requisito: mostrar valor da linha anterior, atual e proxima
-- Tabela escolhida: reward_point (coluna: points)
-- =============================================================

DECLARE
  CURSOR c_lag_lead IS
    SELECT
      rp.id                                                    AS id_registro,
      t.name                                                   AS tutor,
      ra.name                                                  AS acao,
      rp.points                                                AS pts_atual,
      LAG(rp.points)  OVER (ORDER BY rp.id)                   AS pts_anterior,
      LEAD(rp.points) OVER (ORDER BY rp.id)                   AS pts_proximo
    FROM reward_point rp
    JOIN tutor        t  ON t.id  = rp.tutor_id
    JOIN reward_action ra ON ra.id = rp.reward_action_id
    ORDER BY rp.id;

  v_anterior VARCHAR2(20);
  v_proximo  VARCHAR2(20);
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('HISTORICO DE PONTOS: ANTERIOR | ATUAL | PROXIMO');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(
    RPAD('ID',5) ||
    RPAD('Tutor',20) ||
    RPAD('Acao',30) ||
    LPAD('Anterior',12) ||
    LPAD('Atual',10) ||
    LPAD('Proximo',10)
  );
  DBMS_OUTPUT.PUT_LINE(RPAD('-',87,'-'));

  FOR r IN c_lag_lead LOOP
    v_anterior := CASE WHEN r.pts_anterior IS NULL THEN 'Vazio' ELSE TO_CHAR(r.pts_anterior) END;
    v_proximo  := CASE WHEN r.pts_proximo  IS NULL THEN 'Vazio' ELSE TO_CHAR(r.pts_proximo)  END;

    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.id_registro, 5) ||
      RPAD(r.tutor,       20) ||
      RPAD(r.acao,        30) ||
      LPAD(v_anterior,    12) ||
      LPAD(r.pts_atual,   10) ||
      LPAD(v_proximo,     10)
    );
  END LOOP;
END;
/


-- =============================================================
-- SECAO 7: RELATORIOS COM CURSOR EXPLICITO E TOMADA DE DECISAO
-- Requisito: 4 blocos com cursor explicito, decisao (IF/CASE),
-- sumarizacao e agrupamento
-- =============================================================

-- -------------------------
-- Relatorio 7.1
-- Extrato de pontos por tutor com classificacao de nivel
-- -------------------------
DECLARE
  CURSOR c_pontos IS
    SELECT
      t.name       AS tutor_nome,
      SUM(rp.points) AS total_pontos
    FROM tutor t
    JOIN reward_point rp ON rp.tutor_id = t.id
    GROUP BY t.name
    ORDER BY total_pontos DESC;

  v_nivel      VARCHAR2(20);
  v_total_geral NUMBER := 0;
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('RELATORIO 1: EXTRATO DE PONTOS POR TUTOR');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Tutor',25) || LPAD('Pontos',12) || RPAD('  Nivel',15));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',52,'-'));

  FOR r IN c_pontos LOOP
    v_total_geral := v_total_geral + r.total_pontos;

    v_nivel := CASE
      WHEN r.total_pontos >= 500 THEN 'OURO'
      WHEN r.total_pontos >= 200 THEN 'PRATA'
      WHEN r.total_pontos >= 100 THEN 'BRONZE'
      ELSE                            'INICIANTE'
    END;

    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.tutor_nome, 25) ||
      LPAD(r.total_pontos, 12) ||
      '  ' || v_nivel
    );
  END LOOP;

  DBMS_OUTPUT.PUT_LINE(RPAD('-',52,'-'));
  DBMS_OUTPUT.PUT_LINE(RPAD('TOTAL GERAL', 25) || LPAD(v_total_geral, 12));
END;
/

-- -------------------------
-- Relatorio 7.2
-- Status dos pets por tutor com alertas de risco
-- -------------------------
DECLARE
  CURSOR c_pets_risco IS
    SELECT
      t.name        AS tutor_nome,
      p.name        AS pet_nome,
      s.name        AS especie,
      rs.score      AS score_risco,
      rl.name       AS nivel_risco
    FROM pet p
    JOIN tutor      t  ON t.id  = p.tutor_id
    JOIN species    s  ON s.id  = p.species_id
    LEFT JOIN (
      SELECT pet_id, score, risk_level_id,
             ROW_NUMBER() OVER (PARTITION BY pet_id ORDER BY calculated_at DESC) AS rn
      FROM risk_score
    ) rs ON rs.pet_id = p.id AND rs.rn = 1
    LEFT JOIN risk_level rl ON rl.id = rs.risk_level_id
    ORDER BY t.name, rs.score DESC NULLS LAST;

  v_alerta    VARCHAR2(50);
  v_qtd_alto  NUMBER := 0;
  v_qtd_total NUMBER := 0;
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('RELATORIO 2: SITUACAO DE RISCO DOS PETS');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Tutor',20) || RPAD('Pet',15) || RPAD('Especie',12) || LPAD('Score',8) || RPAD('  Nivel',12) || 'Alerta');
  DBMS_OUTPUT.PUT_LINE(RPAD('-',85,'-'));

  FOR r IN c_pets_risco LOOP
    v_qtd_total := v_qtd_total + 1;

    IF r.nivel_risco IN ('Alto','Critico') THEN
      v_alerta   := '*** ATENCAO ***';
      v_qtd_alto := v_qtd_alto + 1;
    ELSIF r.nivel_risco = 'Medio' THEN
      v_alerta := 'Monitorar';
    ELSE
      v_alerta := 'Ok';
    END IF;

    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.tutor_nome,  20) ||
      RPAD(r.pet_nome,    15) ||
      RPAD(r.especie,     12) ||
      LPAD(NVL(TO_CHAR(r.score_risco), '-'), 8) ||
      '  ' || RPAD(NVL(r.nivel_risco, '-'), 12) ||
      v_alerta
    );
  END LOOP;

  DBMS_OUTPUT.PUT_LINE(RPAD('-',85,'-'));
  DBMS_OUTPUT.PUT_LINE('Total de pets analisados : ' || v_qtd_total);
  DBMS_OUTPUT.PUT_LINE('Pets em situacao de risco: ' || v_qtd_alto);
END;
/

-- -------------------------
-- Relatorio 7.3
-- Cupons disponiveis agrupados por parceiro e tipo de desconto
-- -------------------------
DECLARE
  CURSOR c_cupons IS
    SELECT
      pd.partner_name                   AS parceiro,
      ct.discount_type                  AS tipo_desconto,
      COUNT(cu.id)                      AS qtd_cupons,
      SUM(ct.discount_value)            AS valor_total_descontos,
      MIN(ct.points_required)           AS menor_custo_pts,
      MAX(ct.points_required)           AS maior_custo_pts
    FROM coupon cu
    JOIN coupon_template  ct ON ct.id = cu.template_id
    JOIN partner_discount pd ON pd.id = ct.partner_discount_id
    WHERE cu.status = 'DISPONIVEL'
    GROUP BY pd.partner_name, ct.discount_type
    ORDER BY pd.partner_name, ct.discount_type;

  v_subtotal_qtd    NUMBER := 0;
  v_subtotal_valor  NUMBER := 0;
  v_parceiro_atual  VARCHAR2(100) := '';
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('RELATORIO 3: CUPONS DISPONIVEIS POR PARCEIRO');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Parceiro',25) || RPAD('Tipo',15) || LPAD('Qtd',8) || LPAD('Valor Total',15) || LPAD('Pts Min',10) || LPAD('Pts Max',10));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',83,'-'));

  FOR r IN c_cupons LOOP
    IF v_parceiro_atual != r.parceiro AND v_parceiro_atual != '' THEN
      DBMS_OUTPUT.PUT_LINE(RPAD(' >> Sub-Total ' || v_parceiro_atual, 40) ||
                           LPAD(v_subtotal_qtd, 8) ||
                           LPAD(TO_CHAR(v_subtotal_valor,'FM99990.00'), 15));
      DBMS_OUTPUT.PUT_LINE(RPAD('-',83,'-'));
      v_subtotal_qtd   := 0;
      v_subtotal_valor := 0;
    END IF;

    v_parceiro_atual := r.parceiro;
    v_subtotal_qtd   := v_subtotal_qtd   + r.qtd_cupons;
    v_subtotal_valor := v_subtotal_valor + r.valor_total_descontos;

    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.parceiro,       25) ||
      RPAD(r.tipo_desconto,  15) ||
      LPAD(r.qtd_cupons,      8) ||
      LPAD(TO_CHAR(r.valor_total_descontos,'FM99990.00'), 15) ||
      LPAD(r.menor_custo_pts, 10) ||
      LPAD(r.maior_custo_pts, 10)
    );
  END LOOP;

  IF v_parceiro_atual != '' THEN
    DBMS_OUTPUT.PUT_LINE(RPAD(' >> Sub-Total ' || v_parceiro_atual, 40) ||
                         LPAD(v_subtotal_qtd, 8) ||
                         LPAD(TO_CHAR(v_subtotal_valor,'FM99990.00'), 15));
  END IF;
END;
/

-- -------------------------
-- Relatorio 7.4
-- Producao de eventos de saude por mes e categoria
-- Sub-totais por categoria e total geral
-- -------------------------
DECLARE
  CURSOR c_eventos_mes IS
    SELECT
      TO_CHAR(he.event_date, 'YYYY-MM')  AS mes,
      et.category                         AS categoria,
      COUNT(he.id)                        AS qtd_eventos,
      SUM(et.points_reward)               AS pts_distribuidos
    FROM health_event he
    JOIN event_type et ON et.id = he.event_type_id
    WHERE he.status = 'REALIZADO'
    GROUP BY TO_CHAR(he.event_date, 'YYYY-MM'), et.category
    ORDER BY mes, categoria;

  v_cat_atual      VARCHAR2(50) := '';
  v_sub_qtd        NUMBER := 0;
  v_sub_pts        NUMBER := 0;
  v_total_qtd      NUMBER := 0;
  v_total_pts      NUMBER := 0;
BEGIN
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('RELATORIO 4: EVENTOS DE SAUDE POR MES E CATEGORIA');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Mes',12) || RPAD('Categoria',20) || LPAD('Qtd',10) || LPAD('Pts Dist.',15));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',57,'-'));

  FOR r IN c_eventos_mes LOOP

    IF v_cat_atual != r.categoria AND v_cat_atual != '' THEN
      DBMS_OUTPUT.PUT_LINE(
        RPAD(' > Sub-Total ' || v_cat_atual, 32) ||
        LPAD(v_sub_qtd, 10) ||
        LPAD(v_sub_pts, 15)
      );
      DBMS_OUTPUT.PUT_LINE(RPAD('-',57,'-'));
      v_sub_qtd := 0;
      v_sub_pts := 0;
    END IF;

    v_cat_atual  := r.categoria;
    v_sub_qtd    := v_sub_qtd   + r.qtd_eventos;
    v_sub_pts    := v_sub_pts   + r.pts_distribuidos;
    v_total_qtd  := v_total_qtd + r.qtd_eventos;
    v_total_pts  := v_total_pts + r.pts_distribuidos;

    DBMS_OUTPUT.PUT_LINE(
      RPAD(r.mes,        12) ||
      RPAD(r.categoria,  20) ||
      LPAD(r.qtd_eventos, 10) ||
      LPAD(r.pts_distribuidos, 15)
    );
  END LOOP;

  IF v_cat_atual != '' THEN
    DBMS_OUTPUT.PUT_LINE(
      RPAD(' > Sub-Total ' || v_cat_atual, 32) ||
      LPAD(v_sub_qtd, 10) ||
      LPAD(v_sub_pts, 15)
    );
  END IF;

  DBMS_OUTPUT.PUT_LINE(RPAD('=',57,'='));
  DBMS_OUTPUT.PUT_LINE(RPAD('TOTAL GERAL', 32) || LPAD(v_total_qtd, 10) || LPAD(v_total_pts, 15));
END;
/

-- -------------------------
-- Testes finais / Relatórios
-- -------------------------

SELECT * FROM SPECIES;

SELECT * FROM TUTOR;

SELECT * FROM CLINIC;

SELECT * FROM PET;

SELECT * FROM EVENT_TYPE;

SELECT * FROM RISK_LEVEL;

SELECT object_name, status
FROM user_objects
WHERE object_type = 'PROCEDURE';

SELECT
    t.name AS tutor,
    COUNT(p.id) AS quantidade_pets
FROM tutor t
JOIN pet p ON p.tutor_id = t.id
GROUP BY t.name
ORDER BY quantidade_pets DESC;

SELECT
    p.name AS pet,
    COUNT(h.id) AS total_eventos
FROM pet p
JOIN health_event h ON h.pet_id = p.id
GROUP BY p.name
ORDER BY total_eventos DESC;

SELECT
    c.name AS clinica,
    COUNT(h.id) AS eventos
FROM clinic c
JOIN health_event h ON h.clinic_id = c.id
GROUP BY c.name
ORDER BY eventos DESC;

SELECT
    pet_id,

    score AS score_atual,

    NVL(
        TO_CHAR(
            LAG(score)
            OVER (ORDER BY id)
        ),
        'Vazio'
    ) AS score_anterior,

    NVL(
        TO_CHAR(
            LEAD(score)
            OVER (ORDER BY id)
        ),
        'Vazio'
    ) AS score_proximo

FROM risk_score;

SET SERVEROUTPUT ON;

DECLARE

    CURSOR c_pets IS
        SELECT name, weight
        FROM pet;

    v_name pet.name%TYPE;
    v_weight pet.weight%TYPE;

BEGIN

    OPEN c_pets;

    LOOP

        FETCH c_pets INTO v_name, v_weight;

        EXIT WHEN c_pets%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Pet: ' || v_name ||
            ' | Peso: ' || v_weight
        );

    END LOOP;

    CLOSE c_pets;

END;
/


-- =============================================================
-- SECAO 8: REQUISITOS DA SPRINT 3 - MASTERING RELATIONAL AND
--          NON-RELATIONAL DATABASE
-- Conteudo desta secao:
--   8.1 Funcao 1  - Conversao manual de dados relacionais para JSON
--   8.2 Funcao 2  - Validacao de senha (logica de negocio)
--   8.3 Procedure 1 - JOIN entre tabelas + saida em JSON (usa Funcao 1)
--   8.4 Procedure 2 - Tabela de fatos com subtotal e total geral manual
--   8.5 Trigger de auditoria (DML) com tabela de log
--   8.6 Bloco de demonstracao / execucao de tudo acima
-- =============================================================


-- =============================================================
-- 8.1 FUNCAO 1
-- Recebe dados relacionais (do JOIN pet + tutor + species) e
-- retorna uma string no formato JSON, montada manualmente via
-- concatenacao de string. Proibido TO_JSON / JSON_OBJECT / etc.
-- Trata no minimo 3 excecoes distintas.
-- =============================================================
CREATE OR REPLACE FUNCTION fn_pet_tutor_to_json (
  p_pet_id      IN pet.id%TYPE,
  p_pet_name    IN pet.name%TYPE,
  p_breed       IN pet.breed%TYPE,
  p_weight      IN pet.weight%TYPE,
  p_tutor_name  IN tutor.name%TYPE,
  p_species_nm  IN species.name%TYPE
) RETURN VARCHAR2
AS
  v_usuario   VARCHAR2(100);
  v_sqlcode   NUMBER;
  v_sqlerrm   VARCHAR2(4000);
  v_json      VARCHAR2(4000);
  v_breed     VARCHAR2(60);
  v_weight    VARCHAR2(20);

  ex_id_nulo    EXCEPTION;
  ex_nome_nulo  EXCEPTION;
  ex_json_grande EXCEPTION;
BEGIN
  v_usuario := USER;

  -- Excecao 1: identificador obrigatorio
  IF p_pet_id IS NULL THEN
    RAISE ex_id_nulo;
  END IF;

  -- Excecao 2: campos textuais obrigatorios para montar o JSON
  IF p_pet_name IS NULL OR p_tutor_name IS NULL THEN
    RAISE ex_nome_nulo;
  END IF;

  -- Escape manual de aspas duplas nos campos de texto (regra basica de JSON)
  v_breed  := REPLACE(NVL(p_breed, ''), '"', '\"');
  v_weight := CASE WHEN p_weight IS NULL THEN 'null' ELSE TO_CHAR(p_weight) END;

  v_json :=
    '{'                                                              ||
    '"pet_id":'      || p_pet_id                                     || ',' ||
    '"pet_name":"'   || REPLACE(p_pet_name, '"', '\"')  || '",'      ||
    '"breed":"'      || v_breed                          || '",'    ||
    '"weight":'      || v_weight                                     || ',' ||
    '"tutor_name":"' || REPLACE(p_tutor_name, '"', '\"') || '",'     ||
    '"species":"'    || REPLACE(NVL(p_species_nm,''), '"', '\"') || '"' ||
    '}';

  -- Excecao 3: protecao contra JSON fora do tamanho suportado pela variavel
  IF LENGTH(v_json) > 4000 THEN
    RAISE ex_json_grande;
  END IF;

  RETURN v_json;

EXCEPTION
  WHEN ex_id_nulo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_pet_tutor_to_json', v_usuario, -20040, 'ID do pet nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20040, 'ID do pet nao pode ser nulo');

  WHEN ex_nome_nulo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_pet_tutor_to_json', v_usuario, -20041, 'Nome do pet ou do tutor nao pode ser nulo');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20041, 'Nome do pet ou do tutor nao pode ser nulo');

  WHEN ex_json_grande THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_pet_tutor_to_json', v_usuario, -20042, 'JSON gerado excede o tamanho maximo suportado');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20042, 'JSON gerado excede o tamanho maximo suportado');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_pet_tutor_to_json', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END fn_pet_tutor_to_json;
/


-- =============================================================
-- 8.2 FUNCAO 2
-- Funcao que substitui um processo logico do projeto: validacao
-- de senha de tutor antes do cadastro. Trata no minimo 3 excecoes.
-- =============================================================
CREATE OR REPLACE FUNCTION fn_validar_senha (
  p_senha IN VARCHAR2
) RETURN VARCHAR2
AS
  v_usuario VARCHAR2(100);
  v_sqlcode NUMBER;
  v_sqlerrm VARCHAR2(4000);

  ex_senha_nula       EXCEPTION;
  ex_senha_curta      EXCEPTION;
  ex_senha_sem_numero EXCEPTION;
  ex_senha_sem_letra  EXCEPTION;
BEGIN
  v_usuario := USER;

  -- Excecao 1
  IF p_senha IS NULL THEN
    RAISE ex_senha_nula;
  END IF;

  -- Excecao 2
  IF LENGTH(p_senha) < 8 THEN
    RAISE ex_senha_curta;
  END IF;

  -- Excecao 3
  IF NOT REGEXP_LIKE(p_senha, '[0-9]') THEN
    RAISE ex_senha_sem_numero;
  END IF;

  -- Excecao 4
  IF NOT REGEXP_LIKE(p_senha, '[A-Za-z]') THEN
    RAISE ex_senha_sem_letra;
  END IF;

  RETURN 'SENHA_VALIDA';

EXCEPTION
  WHEN ex_senha_nula THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_validar_senha', v_usuario, -20050, 'Senha nao pode ser nula');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20050, 'Senha nao pode ser nula');

  WHEN ex_senha_curta THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_validar_senha', v_usuario, -20051, 'Senha deve ter no minimo 8 caracteres');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20051, 'Senha deve ter no minimo 8 caracteres');

  WHEN ex_senha_sem_numero THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_validar_senha', v_usuario, -20052, 'Senha deve conter ao menos um numero');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20052, 'Senha deve conter ao menos um numero');

  WHEN ex_senha_sem_letra THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_validar_senha', v_usuario, -20053, 'Senha deve conter ao menos uma letra');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20053, 'Senha deve conter ao menos uma letra');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('fn_validar_senha', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END fn_validar_senha;
/


-- =============================================================
-- 8.3 PROCEDURE 1
-- JOIN entre tutor, pet e species (3 tabelas relacionais, cada
-- uma com >= 5 registros validos). Para cada linha, chama a
-- Funcao 1 para montar o JSON manualmente. Trata >= 3 excecoes.
-- =============================================================
CREATE OR REPLACE PROCEDURE sp_relatorio_pets_json
AS
  v_usuario     VARCHAR2(100);
  v_sqlcode     NUMBER;
  v_sqlerrm     VARCHAR2(4000);
  v_json        VARCHAR2(4000);
  v_encontrou   BOOLEAN := FALSE;

  ex_sem_dados       EXCEPTION;
  ex_falha_conversao EXCEPTION;

  CURSOR c_pets IS
    SELECT
      p.id      AS pet_id,
      p.name    AS pet_name,
      p.breed   AS breed,
      p.weight  AS weight,
      t.name    AS tutor_name,
      s.name    AS species_name
    FROM pet p
    JOIN tutor   t ON t.id = p.tutor_id
    JOIN species s ON s.id = p.species_id
    ORDER BY t.name, p.name;
BEGIN
  v_usuario := USER;

  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('PROCEDURE 1: PETS + TUTORES + ESPECIES (JSON)');
  DBMS_OUTPUT.PUT_LINE('==============================================');

  FOR r IN c_pets LOOP
    v_encontrou := TRUE;

    BEGIN
      v_json := fn_pet_tutor_to_json(
                  p_pet_id     => r.pet_id,
                  p_pet_name   => r.pet_name,
                  p_breed      => r.breed,
                  p_weight     => r.weight,
                  p_tutor_name => r.tutor_name,
                  p_species_nm => r.species_name
                );
    EXCEPTION
      WHEN OTHERS THEN
        RAISE ex_falha_conversao;
    END;

    DBMS_OUTPUT.PUT_LINE(v_json);
  END LOOP;

  -- Excecao: cursor sem nenhuma linha retornada
  IF NOT v_encontrou THEN
    RAISE ex_sem_dados;
  END IF;

EXCEPTION
  WHEN ex_sem_dados THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_relatorio_pets_json', v_usuario, -20060, 'Nenhum registro encontrado para o JOIN pet/tutor/species');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20060, 'Nenhum registro encontrado para gerar o JSON');

  WHEN ex_falha_conversao THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_relatorio_pets_json', v_usuario, -20061, 'Falha ao converter linha para JSON via fn_pet_tutor_to_json');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20061, 'Falha ao converter linha para JSON');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_relatorio_pets_json', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_relatorio_pets_json;
/


-- =============================================================
-- 8.4 PROCEDURE 2
-- Le dados de uma "tabela de fatos" (reward_point, associada a
-- tutor e reward_action) que possui duas colunas categoricas
-- (tutor / acao de recompensa) e uma coluna numerica (pontos).
-- Calcula manualmente, DENTRO do procedimento, sem ROLLUP/CUBE/
-- GROUPING SETS:
--   - soma por combinacao completa (tutor, acao)
--   - subtotal por tutor (primeira categoria)
--   - total geral ao final
-- Ordem de saida segue a hierarquia das categorias, com colunas
-- de agrupamento nulas nas linhas de subtotal/total geral.
-- Trata >= 3 excecoes.
-- =============================================================
CREATE OR REPLACE PROCEDURE sp_relatorio_pontos_categoria
AS
  v_usuario         VARCHAR2(100);
  v_sqlcode         NUMBER;
  v_sqlerrm         VARCHAR2(4000);

  v_tutor_atual     tutor.name%TYPE := NULL;
  v_acao_atual      reward_action.name%TYPE := NULL;
  v_soma_combo      NUMBER := 0;
  v_subtotal_tutor  NUMBER := 0;
  v_total_geral     NUMBER := 0;
  v_primeira_linha  BOOLEAN := TRUE;
  v_encontrou       BOOLEAN := FALSE;

  ex_sem_dados       EXCEPTION;
  ex_valor_negativo  EXCEPTION;

  -- Cursor ja ordenado pela hierarquia das categorias (tutor, acao).
  -- A soma da combinacao (tutor, acao) e feita linha a linha, dentro
  -- do proprio bloco PL/SQL (controle de quebra manual), sem usar
  -- ROLLUP/CUBE/GROUPING SETS.
  CURSOR c_fatos IS
    SELECT
      t.name  AS tutor_name,
      ra.name AS acao_name,
      rp.points AS pontos
    FROM reward_point rp
    JOIN tutor         t  ON t.id  = rp.tutor_id
    JOIN reward_action ra ON ra.id = rp.reward_action_id
    ORDER BY t.name, ra.name;

  PROCEDURE imprimir_combo IS
  BEGIN
    IF v_tutor_atual IS NOT NULL AND v_acao_atual IS NOT NULL THEN
      DBMS_OUTPUT.PUT_LINE(
        RPAD(v_tutor_atual, 20) ||
        RPAD(v_acao_atual, 30) ||
        LPAD(v_soma_combo, 12)
      );
    END IF;
  END imprimir_combo;

BEGIN
  v_usuario := USER;

  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE('PROCEDURE 2: PONTOS POR TUTOR E ACAO (SEM ROLLUP)');
  DBMS_OUTPUT.PUT_LINE('==============================================');
  DBMS_OUTPUT.PUT_LINE(RPAD('Tutor',20) || RPAD('Acao',30) || LPAD('Pontos',12));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',62,'-'));

  FOR r IN c_fatos LOOP
    v_encontrou := TRUE;

    IF r.pontos < 0 THEN
      RAISE ex_valor_negativo;
    END IF;

    -- Quebra de combo (tutor + acao mudou): imprime combo anterior
    IF NOT v_primeira_linha AND (r.tutor_name != v_tutor_atual OR r.acao_name != v_acao_atual) THEN
      imprimir_combo;
      v_soma_combo := 0;
    END IF;

    -- Quebra de tutor (primeira categoria mudou): imprime subtotal
    IF NOT v_primeira_linha AND r.tutor_name != v_tutor_atual THEN
      DBMS_OUTPUT.PUT_LINE(
        RPAD('  Sub Total ' || v_tutor_atual, 50) ||
        LPAD(v_subtotal_tutor, 12)
      );
      DBMS_OUTPUT.PUT_LINE(RPAD('-',62,'-'));
      v_subtotal_tutor := 0;
    END IF;

    v_tutor_atual    := r.tutor_name;
    v_acao_atual     := r.acao_name;
    v_soma_combo      := v_soma_combo      + r.pontos;
    v_subtotal_tutor  := v_subtotal_tutor  + r.pontos;
    v_total_geral     := v_total_geral     + r.pontos;
    v_primeira_linha  := FALSE;
  END LOOP;

  IF NOT v_encontrou THEN
    RAISE ex_sem_dados;
  END IF;

  -- Imprime o ultimo combo e o ultimo subtotal pendentes
  imprimir_combo;
  DBMS_OUTPUT.PUT_LINE(
    RPAD('  Sub Total ' || v_tutor_atual, 50) ||
    LPAD(v_subtotal_tutor, 12)
  );
  DBMS_OUTPUT.PUT_LINE(RPAD('=',62,'='));
  DBMS_OUTPUT.PUT_LINE(RPAD('Total Geral', 50) || LPAD(v_total_geral, 12));

EXCEPTION
  WHEN ex_sem_dados THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_relatorio_pontos_categoria', v_usuario, -20070, 'Nenhum registro encontrado em reward_point');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20070, 'Nenhum registro encontrado em reward_point');

  WHEN ex_valor_negativo THEN
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_relatorio_pontos_categoria', v_usuario, -20071, 'Valor de pontos negativo encontrado na tabela de fatos');
    COMMIT;
    RAISE_APPLICATION_ERROR(-20071, 'Valor de pontos negativo encontrado');

  WHEN OTHERS THEN
    v_sqlcode := SQLCODE;
    v_sqlerrm := SQLERRM;
    INSERT INTO log_erros (procedure_name, usuario, codigo_erro, mensagem_erro)
    VALUES ('sp_relatorio_pontos_categoria', v_usuario, v_sqlcode, v_sqlerrm);
    COMMIT;
    RAISE;
END sp_relatorio_pontos_categoria;
/


-- =============================================================
-- 8.5 TRIGGER DE AUDITORIA (DML)
-- Tabela de auditoria com: usuario, tipo de operacao, data/hora,
-- valores anteriores (:OLD) e valores novos (:NEW).
-- Trigger AFTER INSERT OR UPDATE OR DELETE ON health_event
-- (tabela central de eventos clinicos do pet), FOR EACH ROW.
-- =============================================================

CREATE TABLE log_auditoria_health_event (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_usuario      VARCHAR2(100) NOT NULL,
  tipo_operacao     VARCHAR2(10)  NOT NULL,
  -- tipo: 'INSERT', 'UPDATE', 'DELETE'
  data_hora         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  valores_anteriores VARCHAR2(4000),
  valores_novos      VARCHAR2(4000)
);

CREATE OR REPLACE TRIGGER trg_audit_health_event
AFTER INSERT OR UPDATE OR DELETE ON health_event
FOR EACH ROW
DECLARE
  v_tipo_operacao    VARCHAR2(10);
  v_valores_antigos  VARCHAR2(4000);
  v_valores_novos    VARCHAR2(4000);
BEGIN
  IF INSERTING THEN
    v_tipo_operacao   := 'INSERT';
    v_valores_antigos := NULL;
    v_valores_novos   := 'ID=' || :NEW.id ||
                         ';PET_ID=' || :NEW.pet_id ||
                         ';EVENT_TYPE_ID=' || :NEW.event_type_id ||
                         ';STATUS=' || :NEW.status ||
                         ';EVENT_DATE=' || TO_CHAR(:NEW.event_date,'YYYY-MM-DD');

  ELSIF UPDATING THEN
    v_tipo_operacao   := 'UPDATE';
    v_valores_antigos := 'ID=' || :OLD.id ||
                         ';PET_ID=' || :OLD.pet_id ||
                         ';EVENT_TYPE_ID=' || :OLD.event_type_id ||
                         ';STATUS=' || :OLD.status ||
                         ';EVENT_DATE=' || TO_CHAR(:OLD.event_date,'YYYY-MM-DD');
    v_valores_novos   := 'ID=' || :NEW.id ||
                         ';PET_ID=' || :NEW.pet_id ||
                         ';EVENT_TYPE_ID=' || :NEW.event_type_id ||
                         ';STATUS=' || :NEW.status ||
                         ';EVENT_DATE=' || TO_CHAR(:NEW.event_date,'YYYY-MM-DD');

  ELSIF DELETING THEN
    v_tipo_operacao   := 'DELETE';
    v_valores_antigos := 'ID=' || :OLD.id ||
                         ';PET_ID=' || :OLD.pet_id ||
                         ';EVENT_TYPE_ID=' || :OLD.event_type_id ||
                         ';STATUS=' || :OLD.status ||
                         ';EVENT_DATE=' || TO_CHAR(:OLD.event_date,'YYYY-MM-DD');
    v_valores_novos   := NULL;
  END IF;

  INSERT INTO log_auditoria_health_event (
    nome_usuario, tipo_operacao, data_hora, valores_anteriores, valores_novos
  ) VALUES (
    USER, v_tipo_operacao, SYSTIMESTAMP, v_valores_antigos, v_valores_novos
  );
END trg_audit_health_event;
/


-- =============================================================
-- 8.6 DEMONSTRACAO / EXECUCAO
-- Blocos para print de tela (evidencia exigida no PDF):
--   a) execucao das duas procedures
--   b) execucao das duas functions (caso valido + excecao)
--   c) INSERT/UPDATE/DELETE em health_event disparando o trigger
--   d) consulta na tabela de auditoria
-- =============================================================

SET SERVEROUTPUT ON;

-- a) Procedure 1
BEGIN
  sp_relatorio_pets_json;
END;
/

-- a) Procedure 2
BEGIN
  sp_relatorio_pontos_categoria;
END;
/

-- b) Function 1 - caso valido
DECLARE
  v_json VARCHAR2(4000);
BEGIN
  v_json := fn_pet_tutor_to_json(1, 'Rex', 'Labrador', 28.5, 'Ana Lima', 'Cachorro');
  DBMS_OUTPUT.PUT_LINE('Funcao 1 (OK): ' || v_json);
END;
/

-- b) Function 1 - forcando excecao (id nulo)
BEGIN
  DBMS_OUTPUT.PUT_LINE(fn_pet_tutor_to_json(NULL, 'Rex', 'Labrador', 28.5, 'Ana Lima', 'Cachorro'));
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Funcao 1 (excecao esperada): ' || SQLERRM);
END;
/

-- b) Function 2 - caso valido
BEGIN
  DBMS_OUTPUT.PUT_LINE('Funcao 2 (OK): ' || fn_validar_senha('SenhaForte123'));
END;
/

-- b) Function 2 - forcando excecao (senha curta)
BEGIN
  DBMS_OUTPUT.PUT_LINE(fn_validar_senha('abc1'));
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Funcao 2 (excecao esperada): ' || SQLERRM);
END;
/

-- c) Demonstracao do trigger de auditoria (INSERT, UPDATE, DELETE)
INSERT INTO health_event (pet_id, event_type_id, clinic_id, description, event_date, status)
VALUES (2, 4, 2, 'Check-up de rotina - auditoria demo', DATE '2025-05-01', 'REALIZADO');
COMMIT;

UPDATE health_event
SET status = 'CANCELADO'
WHERE description = 'Check-up de rotina - auditoria demo';
COMMIT;

DELETE FROM health_event
WHERE description = 'Check-up de rotina - auditoria demo';
COMMIT;

-- d) Consulta na tabela de auditoria (evidencia das 3 operacoes)
SELECT id, nome_usuario, tipo_operacao, data_hora, valores_anteriores, valores_novos
FROM log_auditoria_health_event
ORDER BY id DESC;

-- Consulta no log de erros (evidencia das excecoes tratadas)
SELECT procedure_name, usuario, data_ocorrencia, codigo_erro, mensagem_erro
FROM log_erros
ORDER BY id DESC;
