// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetFlowAPI.Data;

#nullable disable

namespace PetFlowAPI.Migrations
{
    [DbContext(typeof(PetFlowContext))]
    partial class PetFlowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // TUTOR
            modelBuilder.Entity("PetFlowAPI.Models.Tutor", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("EMAIL");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("NAME");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("NVARCHAR2(255)").HasColumnName("PASSWORD_HASH");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("PHONE");
                b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("ROLE");
                b.HasKey("Id");
                b.ToTable("TUTOR");
            });

            // ADDRESS
            modelBuilder.Entity("PetFlowAPI.Models.Address", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("City").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("CITY");
                b.Property<string>("State").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("STATE");
                b.Property<string>("Street").IsRequired().HasMaxLength(200).HasColumnType("NVARCHAR2(200)").HasColumnName("STREET");
                b.Property<long>("TutorId").HasColumnType("NUMBER(19)").HasColumnName("TUTOR_ID");
                b.Property<string>("ZipCode").IsRequired().HasMaxLength(10).HasColumnType("NVARCHAR2(10)").HasColumnName("ZIP_CODE");
                b.HasKey("Id");
                b.HasIndex("TutorId");
                b.ToTable("ADDRESS");
            });

            // SPECIES
            modelBuilder.Entity("PetFlowAPI.Models.Species", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("NVARCHAR2(200)").HasColumnName("DESCRIPTION");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("NAME");
                b.HasKey("Id");
                b.ToTable("SPECIES");
            });

            // PET
            modelBuilder.Entity("PetFlowAPI.Models.Pet", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<DateTime?>("BirthDate").HasColumnType("DATE").HasColumnName("BIRTH_DATE");
                b.Property<string>("Breed").HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("BREED");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("NAME");
                b.Property<long>("SpeciesId").HasColumnType("NUMBER(19)").HasColumnName("SPECIES_ID");
                b.Property<long>("TutorId").HasColumnType("NUMBER(19)").HasColumnName("TUTOR_ID");
                b.Property<decimal?>("Weight").HasPrecision(5, 2).HasColumnType("NUMBER(5,2)").HasColumnName("WEIGHT");
                b.HasKey("Id");
                b.HasIndex("TutorId");
                b.HasIndex("SpeciesId");
                b.ToTable("PET");
            });

            // CLINIC
            modelBuilder.Entity("PetFlowAPI.Models.Clinic", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("Address").HasMaxLength(200).HasColumnType("NVARCHAR2(200)").HasColumnName("ADDRESS");
                b.Property<string>("Cnpj").HasMaxLength(18).HasColumnType("NVARCHAR2(18)").HasColumnName("CNPJ");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("NAME");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("PHONE");
                b.HasKey("Id");
                b.ToTable("CLINIC");
            });

            // PLAN
            modelBuilder.Entity("PetFlowAPI.Models.Plan", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<long>("ClinicId").HasColumnType("NUMBER(19)").HasColumnName("CLINIC_ID");
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("NVARCHAR2(200)").HasColumnName("DESCRIPTION");
                b.Property<int>("DurationDays").HasColumnType("NUMBER(10)").HasColumnName("DURATION_DAYS");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("NAME");
                b.Property<int>("PointsPerEvent").HasColumnType("NUMBER(10)").HasColumnName("POINTS_PER_EVENT");
                b.Property<decimal>("Price").HasPrecision(10, 2).HasColumnType("NUMBER(10,2)").HasColumnName("PRICE");
                b.HasKey("Id");
                b.HasIndex("ClinicId");
                b.ToTable("PLAN");
            });

            // EVENT_TYPE
            modelBuilder.Entity("PetFlowAPI.Models.EventType", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("CATEGORY");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("NAME");
                b.Property<int>("PointsReward").HasColumnType("NUMBER(10)").HasColumnName("POINTS_REWARD");
                b.HasKey("Id");
                b.ToTable("EVENT_TYPE");
            });

            // HEALTH_EVENT
            modelBuilder.Entity("PetFlowAPI.Models.HealthEvent", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<long?>("ClinicId").HasColumnType("NUMBER(19)").HasColumnName("CLINIC_ID");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("NVARCHAR2(200)").HasColumnName("DESCRIPTION");
                b.Property<DateTime>("EventDate").HasColumnType("DATE").HasColumnName("EVENT_DATE");
                b.Property<long>("EventTypeId").HasColumnType("NUMBER(19)").HasColumnName("EVENT_TYPE_ID");
                b.Property<long>("PetId").HasColumnType("NUMBER(19)").HasColumnName("PET_ID");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("STATUS");
                b.HasKey("Id");
                b.HasIndex("PetId");
                b.HasIndex("EventTypeId");
                b.HasIndex("ClinicId");
                b.ToTable("HEALTH_EVENT");
            });

            // SUBSCRIPTION
            modelBuilder.Entity("PetFlowAPI.Models.Subscription", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<DateTime?>("EndDate").HasColumnType("DATE").HasColumnName("END_DATE");
                b.Property<long>("PetId").HasColumnType("NUMBER(19)").HasColumnName("PET_ID");
                b.Property<long>("PlanId").HasColumnType("NUMBER(19)").HasColumnName("PLAN_ID");
                b.Property<DateTime>("StartDate").HasColumnType("DATE").HasColumnName("START_DATE");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("STATUS");
                b.HasKey("Id");
                b.HasIndex("PetId");
                b.HasIndex("PlanId");
                b.ToTable("SUBSCRIPTION");
            });

            // REWARD_ACTION
            modelBuilder.Entity("PetFlowAPI.Models.RewardAction", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("NVARCHAR2(200)").HasColumnName("DESCRIPTION");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("NAME");
                b.Property<int>("PointsValue").HasColumnType("NUMBER(10)").HasColumnName("POINTS_VALUE");
                b.HasKey("Id");
                b.ToTable("REWARD_ACTION");
            });

            // REWARD_POINT
            modelBuilder.Entity("PetFlowAPI.Models.RewardPoint", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<int>("Points").HasColumnType("NUMBER(10)").HasColumnName("POINTS");
                b.Property<long?>("ReferenceId").HasColumnType("NUMBER(19)").HasColumnName("REFERENCE_ID");
                b.Property<string>("ReferenceType").HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("REFERENCE_TYPE");
                b.Property<long>("RewardActionId").HasColumnType("NUMBER(19)").HasColumnName("REWARD_ACTION_ID");
                b.Property<long>("TutorId").HasColumnType("NUMBER(19)").HasColumnName("TUTOR_ID");
                b.HasKey("Id");
                b.HasIndex("TutorId");
                b.HasIndex("RewardActionId");
                b.ToTable("REWARD_POINT");
            });

            // PARTNER_DISCOUNT
            modelBuilder.Entity("PetFlowAPI.Models.PartnerDiscount", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("CATEGORY");
                b.Property<long>("ClinicId").HasColumnType("NUMBER(19)").HasColumnName("CLINIC_ID");
                b.Property<decimal>("DiscountPercent").HasPrecision(5, 2).HasColumnType("NUMBER(5,2)").HasColumnName("DISCOUNT_PERCENT");
                b.Property<string>("PartnerName").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("PARTNER_NAME");
                b.HasKey("Id");
                b.HasIndex("ClinicId");
                b.ToTable("PARTNER_DISCOUNT");
            });

            // COUPON_TEMPLATE
            modelBuilder.Entity("PetFlowAPI.Models.CouponTemplate", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("DiscountType").IsRequired().HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("DISCOUNT_TYPE");
                b.Property<decimal>("DiscountValue").HasPrecision(10, 2).HasColumnType("NUMBER(10,2)").HasColumnName("DISCOUNT_VALUE");
                b.Property<long>("PartnerDiscountId").HasColumnType("NUMBER(19)").HasColumnName("PARTNER_DISCOUNT_ID");
                b.Property<int>("PointsRequired").HasColumnType("NUMBER(10)").HasColumnName("POINTS_REQUIRED");
                b.Property<string>("Title").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("TITLE");
                b.HasKey("Id");
                b.HasIndex("PartnerDiscountId");
                b.ToTable("COUPON_TEMPLATE");
            });

            // COUPON
            modelBuilder.Entity("PetFlowAPI.Models.Coupon", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("CODE");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<DateTime?>("ExpirationDate").HasColumnType("DATE").HasColumnName("EXPIRATION_DATE");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("NVARCHAR2(20)").HasColumnName("STATUS");
                b.Property<long>("TemplateId").HasColumnType("NUMBER(19)").HasColumnName("TEMPLATE_ID");
                b.HasKey("Id");
                b.HasIndex("TemplateId");
                b.ToTable("COUPON");
            });

            // RISK_LEVEL
            modelBuilder.Entity("PetFlowAPI.Models.RiskLevel", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<string>("Description").HasMaxLength(200).HasColumnType("NVARCHAR2(200)").HasColumnName("DESCRIPTION");
                b.Property<int>("MaxScore").HasColumnType("NUMBER(10)").HasColumnName("MAX_SCORE");
                b.Property<int>("MinScore").HasColumnType("NUMBER(10)").HasColumnName("MIN_SCORE");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("NVARCHAR2(50)").HasColumnName("NAME");
                b.HasKey("Id");
                b.ToTable("RISK_LEVEL");
            });

            // RISK_SCORE
            modelBuilder.Entity("PetFlowAPI.Models.RiskScore", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<DateTime>("CalculatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CALCULATED_AT");
                b.Property<long>("PetId").HasColumnType("NUMBER(19)").HasColumnName("PET_ID");
                b.Property<long>("RiskLevelId").HasColumnType("NUMBER(19)").HasColumnName("RISK_LEVEL_ID");
                b.Property<int>("Score").HasColumnType("NUMBER(10)").HasColumnName("SCORE");
                b.HasKey("Id");
                b.HasIndex("PetId");
                b.HasIndex("RiskLevelId");
                b.ToTable("RISK_SCORE");
            });

            // REDEEM
            modelBuilder.Entity("PetFlowAPI.Models.Redeem", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<long>("CouponId").HasColumnType("NUMBER(19)").HasColumnName("COUPON_ID");
                b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)").HasColumnName("CREATED_AT");
                b.Property<int>("PointsUsed").HasColumnType("NUMBER(10)").HasColumnName("POINTS_USED");
                b.Property<long>("TutorId").HasColumnType("NUMBER(19)").HasColumnName("TUTOR_ID");
                b.HasKey("Id");
                b.HasIndex("TutorId");
                b.HasIndex("CouponId");
                b.ToTable("REDEEM");
            });

            // LOG_ERROS
            modelBuilder.Entity("PetFlowAPI.Models.LogErro", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<int?>("CodigoErro").HasColumnType("NUMBER(10)").HasColumnName("CODIGO_ERRO");
                b.Property<DateTime>("DataOcorrencia").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_OCORRENCIA");
                b.Property<string>("MensagemErro").HasMaxLength(4000).HasColumnType("NVARCHAR2(4000)").HasColumnName("MENSAGEM_ERRO");
                b.Property<string>("ProcedureName").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("PROCEDURE_NAME");
                b.Property<string>("Usuario").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("USUARIO");
                b.HasKey("Id");
                b.ToTable("LOG_ERROS");
            });

            // LOG_AUDITORIA_HEALTH_EVENT
            modelBuilder.Entity("PetFlowAPI.Models.LogAuditoriaHealthEvent", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("NUMBER(19)").HasColumnName("ID");
                b.Property<DateTime>("DataHora").HasColumnType("TIMESTAMP(7)").HasColumnName("DATA_HORA");
                b.Property<string>("NomeUsuario").IsRequired().HasMaxLength(100).HasColumnType("NVARCHAR2(100)").HasColumnName("NOME_USUARIO");
                b.Property<string>("TipoOperacao").IsRequired().HasMaxLength(10).HasColumnType("NVARCHAR2(10)").HasColumnName("TIPO_OPERACAO");
                b.Property<string>("ValoresAnteriores").HasMaxLength(4000).HasColumnType("NVARCHAR2(4000)").HasColumnName("VALORES_ANTERIORES");
                b.Property<string>("ValoresNovos").HasMaxLength(4000).HasColumnType("NVARCHAR2(4000)").HasColumnName("VALORES_NOVOS");
                b.HasKey("Id");
                b.ToTable("LOG_AUDITORIA_HEALTH_EVENT");
            });
#pragma warning restore 612, 618
        }
    }
}
